remote_theme: pages-themes/minimal@v0.2.0
logo: https://avatars.githubusercontent.com/u/11567265
plugins:
- jekyll-remote-theme
title: Manikandan Krishnamurthy
description: #GoogleCloudCertified Architect | Cloud Tech Influencer
show_downloads: False
