title: Manikandan Krishnamurthy
description: "#GoogleCloudCertified Architect | Cloud Tech Influencer"
remote_theme: pages-themes/cayman@v0.2.0
logo: https://avatars.githubusercontent.com/u/11567265
plugins:
- jekyll-remote-theme
show_downloads: False
